# Generated by Django 5.2.8 on 2026-02-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.service'),
        ),
    ]
